# Generated by Django 5.2.1 on 2025-09-19 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.CharField(
                choices=[
                    ("FIC", "Fiction"),
                    ("NF", "Non-Fiction"),
                    ("FAN", "Fantasy"),
                    ("SCI", "Science"),
                    ("HIS", "History"),
                    ("BIO", "Biography"),
                    ("MYS", "Mystery"),
                    ("ROM", "Romance"),
                    ("HOR", "Horror"),
                    ("POE", "Poetry"),
                ],
                default="FIC",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="isbn",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
